<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
      <DebugType>full</DebugType>
      <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ApprovalTests" Version="7.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.1" />
    <PackageReference Include="Microsoft.Win32" Version="2.0.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.10.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.10.4" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\Ecark.ApprovalTests.Excel\Ecark.ApprovalTests.Excel.csproj" />
  </ItemGroup>
    
</Project>