<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ApprovalTests" Version="3.0.8" />
    <PackageReference Include="ApprovalUtilities" Version="3.0.8" />
    <PackageReference Include="DotNetZip" Version="1.9.3" />
  </ItemGroup>
</Project>